var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1,ka=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia=(ja="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!ha;ka=!fa&&!ia&&!ha;var k="",la,ma,na,oa;
if(ia)k=__dirname+"/",la=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",n),ea=function(a){process.exit(a)},
g.inspect=function(){return"[Emscripten Module object]"};else if(ka)"undefined"!=typeof read&&(la=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?k=self.location.href:document.currentScript&&(k=document.currentScript.src),k=0!==k.indexOf("blob:")?k.substr(0,k.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var qa=g.print||console.log.bind(console),p=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);var ra=0,sa;g.wasmBinary&&(sa=g.wasmBinary);var ta;g.noExitRuntime&&(ta=g.noExitRuntime);"object"!==typeof WebAssembly&&p("no native wasm support detected");var ua,va=new WebAssembly.Table({initial:502,maximum:502,element:"anyfunc"}),wa=!1;
function assert(a,b){a||n("Assertion failed: "+b)}function xa(a){var b=g["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ya(a,b,c,d){var e={string:function(q){var r=0;if(null!==q&&void 0!==q&&0!==q){var v=(q.length<<2)+1;r=za(v);u(q,w,r,v)}return r},array:function(q){var r=za(q.length);y.set(q,r);return r}},f=xa(a),h=[];a=0;if(d)for(var m=0;m<d.length;m++){var t=e[c[m]];t?(0===a&&(a=Aa()),h[m]=t(d[m])):h[m]=d[m]}c=f.apply(null,h);c=function(q){return"string"===b?A(q):"boolean"===b?!!q:q}(c);0!==a&&Ba(a);return c}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a,b){return a?Da(w,a,b):""}
function u(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Fa(a){var b=Ea(a)+1,c=za(b);u(a,y,c,b);return c}var buffer,y,w,Ga,Ha,B,Ia,C,D;
function Ja(a){buffer=a;g.HEAP8=y=new Int8Array(a);g.HEAP16=Ga=new Int16Array(a);g.HEAP32=B=new Int32Array(a);g.HEAPU8=w=new Uint8Array(a);g.HEAPU16=Ha=new Uint16Array(a);g.HEAPU32=Ia=new Uint32Array(a);g.HEAPF32=C=new Float32Array(a);g.HEAPF64=D=new Float64Array(a)}var Ka=g.TOTAL_MEMORY||33554432;g.wasmMemory?ua=g.wasmMemory:ua=new WebAssembly.Memory({initial:Ka/65536});ua&&(buffer=ua.buffer);Ka=buffer.byteLength;Ja(buffer);B[1742584]=12213376;
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.yd;"number"===typeof c?void 0===b.ad?g.dynCall_v(c):g.dynCall_vi(c,b.ad):c(void 0===b.ad?null:b.ad)}}}var Ma=[],Na=[],Oa=[],Pa=[],Qa=[];function Ra(){var a=g.preRun.shift();Ma.unshift(a)}var Sa=Math.abs,Ta=Math.ceil,Ua=Math.floor,Va=Math.min,Wa=0,Xa=null,Ya=null;g.preloadedImages={};g.preloadedAudios={};
function n(a){if(g.onAbort)g.onAbort(a);qa(a);p(a);wa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Za(){var a=$a;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var $a="zx-ui.wasm";if(!Za()){var ab=$a;$a=g.locateFile?g.locateFile(ab,k):k+ab}
function bb(){try{if(sa)return new Uint8Array(sa);if(ma)return ma($a);throw"both async and sync fetching of the wasm failed";}catch(a){n(a)}}function cb(){return sa||!fa&&!ha||"function"!==typeof fetch?new Promise(function(a){a(bb())}):fetch($a,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+$a+"'";return a.arrayBuffer()}).catch(function(){return bb()})}
var E,G,fb={3715:function(){db(function(a){a&&console.error(a)})},4901:function(){H("/data");eb(I,"/data");db(!0,function(a){console.error(a)})}};Na.push({yd:function(){gb()}});function hb(a){g.___errno_location&&(B[g.___errno_location()>>2]=a)}function ib(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function jb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ib(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function kb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function lb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function mb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ib(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var nb=[];function ob(a,b){nb[a]={input:[],output:[],Mc:b};pb(a,qb)}
var qb={open:function(a){var b=nb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Mc.flush(a.tty)},flush:function(a){a.tty.Mc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Mc.od)throw new J(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Mc.od(a.tty)}catch(m){throw new J(29);}if(void 0===h&&0===e)throw new J(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Mc.cd)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.Mc.cd(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},sb={od:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Wc?Buffer.Wc(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=rb(b,!0)}return a.input.shift()},cd:function(a,b){null===b||10===b?(qa(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Da(a.output,0)),a.output=[])}},tb={cd:function(a,b){null===b||10===b?(p(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(p(Da(a.output,0)),a.output=[])}},K={Bc:null,zc:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.Bc||(K.Bc={dir:{node:{Ac:K.sc.Ac,wc:K.sc.wc,lookup:K.sc.lookup,Uc:K.sc.Uc,rename:K.sc.rename,unlink:K.sc.unlink,rmdir:K.sc.rmdir,readdir:K.sc.readdir,symlink:K.sc.symlink},stream:{Fc:K.tc.Fc}},file:{node:{Ac:K.sc.Ac,wc:K.sc.wc},stream:{Fc:K.tc.Fc,read:K.tc.read,write:K.tc.write,ed:K.tc.ed,pd:K.tc.pd,Vc:K.tc.Vc}},link:{node:{Ac:K.sc.Ac,wc:K.sc.wc,readlink:K.sc.readlink},stream:{}},jd:{node:{Ac:K.sc.Ac,
wc:K.sc.wc},stream:ub}});c=vb(a,b,c,d);L(c.mode)?(c.sc=K.Bc.dir.node,c.tc=K.Bc.dir.stream,c.rc={}):32768===(c.mode&61440)?(c.sc=K.Bc.file.node,c.tc=K.Bc.file.stream,c.uc=0,c.rc=null):40960===(c.mode&61440)?(c.sc=K.Bc.link.node,c.tc=K.Bc.link.stream):8192===(c.mode&61440)&&(c.sc=K.Bc.jd.node,c.tc=K.Bc.jd.stream);c.timestamp=Date.now();a&&(a.rc[b]=c);return c},Zd:function(a){if(a.rc&&a.rc.subarray){for(var b=[],c=0;c<a.uc;++c)b.push(a.rc[c]);return b}return a.rc},Ad:function(a){return a.rc?a.rc.subarray?
a.rc.subarray(0,a.uc):new Uint8Array(a.rc):new Uint8Array},md:function(a,b){var c=a.rc?a.rc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.rc,a.rc=new Uint8Array(b),0<a.uc&&a.rc.set(c.subarray(0,a.uc),0))},Md:function(a,b){if(a.uc!=b)if(0==b)a.rc=null,a.uc=0;else{if(!a.rc||a.rc.subarray){var c=a.rc;a.rc=new Uint8Array(new ArrayBuffer(b));c&&a.rc.set(c.subarray(0,Math.min(b,a.uc)))}else if(a.rc||(a.rc=[]),a.rc.length>b)a.rc.length=b;else for(;a.rc.length<b;)a.rc.push(0);
a.uc=b}},sc:{Ac:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.uc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.vd=4096;b.blocks=Math.ceil(b.size/b.vd);return b},wc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
K.Md(a,b.size)},lookup:function(){throw wb[44];},Uc:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=xb(b,c)}catch(f){}if(d)for(var e in d.rc)throw new J(55);}delete a.parent.rc[a.name];a.name=c;b.rc[c]=a;a.parent=b},unlink:function(a,b){delete a.rc[b]},rmdir:function(a,b){var c=xb(a,b),d;for(d in c.rc)throw new J(55);delete a.rc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.rc)a.rc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=
K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},tc:{read:function(a,b,c,d,e){var f=a.node.rc;if(e>=a.node.uc)return 0;a=Math.min(a.node.uc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===y.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.rc||a.rc.subarray)){if(f)return a.rc=b.subarray(c,c+d),a.uc=d;if(0===
a.uc&&0===e)return a.rc=new Uint8Array(b.subarray(c,c+d)),a.uc=d;if(e+d<=a.uc)return a.rc.set(b.subarray(c,c+d),e),d}K.md(a,e+d);if(a.rc.subarray&&b.subarray)a.rc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.rc[e+f]=b[c+f];a.uc=Math.max(a.uc,e+d);return d},Fc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.uc);if(0>b)throw new J(28);return b},ed:function(a,b,c){K.md(a.node,b+c);a.node.uc=Math.max(a.node.uc,b+c)},pd:function(a,b,c,d,e,f,h){if(32768!==(a.node.mode&
61440))throw new J(43);c=a.node.rc;if(h&2||c.buffer!==b.buffer){if(0<e||e+d<a.node.uc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==y.buffer;d=M(d);if(!d)throw new J(48);(e?y:b).set(c,d)}else a=!1,d=c.byteOffset;return{fe:d,ud:a}},Vc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.tc.write(a,b,0,d,c,!1);return 0}}},I={kd:{},indexedDB:function(){if("undefined"!==typeof indexedDB)return indexedDB;var a=null;"object"===typeof window&&
(a=window.indexedDB||window.Wc||window.je||window.he);assert(a,"IDBFS used, but indexedDB not supported");return a},td:21,Dc:"FILE_DATA",zc:function(a){return K.zc.apply(null,arguments)},rd:function(a,b,c){I.Bd(a,function(d,e){if(d)return c(d);I.Cd(a,function(f,h){if(f)return c(f);I.Jd(b?h:e,b?e:h,c)})})},zd:function(a,b){var c=I.kd[a];if(c)return b(null,c);try{var d=I.indexedDB().open(a,I.td)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=function(e){var f=
e.target.result;e=e.target.transaction;f=f.objectStoreNames.contains(I.Dc)?e.objectStore(I.Dc):f.createObjectStore(I.Dc);f.indexNames.contains("timestamp")||f.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=function(){c=d.result;I.kd[a]=c;b(null,c)};d.onerror=function(e){b(this.error);e.preventDefault()}},Bd:function(a,b){function c(m){return"."!==m&&".."!==m}function d(m){return function(t){return jb(m+"/"+t)}}var e={};for(a=yb(a.Rc).filter(c).map(d(a.Rc));a.length;){var f=a.pop();
try{var h=zb(f)}catch(m){return b(m)}L(h.mode)&&a.push.apply(a,yb(f).filter(c).map(d(f)));e[f]={timestamp:h.mtime}}return b(null,{type:"local",entries:e})},Cd:function(a,b){var c={};I.zd(a.Rc,function(d,e){if(d)return b(d);try{var f=e.transaction([I.Dc],"readonly");f.onerror=function(h){b(this.error);h.preventDefault()};f.objectStore(I.Dc).index("timestamp").openKeyCursor().onsuccess=function(h){h=h.target.result;if(!h)return b(null,{type:"remote",db:e,entries:c});c[h.primaryKey]={timestamp:h.key};
h.continue()}}catch(h){return b(h)}})},Fd:function(a,b){try{var c=N(a).node;var d=zb(a)}catch(e){return b(e)}return L(d.mode)?b(null,{timestamp:d.mtime,mode:d.mode}):32768===(d.mode&61440)?(c.rc=K.Ad(c),b(null,{timestamp:d.mtime,mode:d.mode,contents:c.rc})):b(Error("node type not supported"))},Od:function(a,b,c){try{if(L(b.mode))H(a,b.mode);else if(32768===(b.mode&61440)){var d=b.contents,e={gd:!0};e=e||{};e.flags=e.flags||"w";var f=Ab(a,e.flags,e.mode);if("string"===typeof d){var h=new Uint8Array(Ea(d)+
1),m=u(d,h,0,h.length);Bb(f,h,0,m,e.gd)}else if(ArrayBuffer.isView(d))Bb(f,d,0,d.byteLength,e.gd);else throw Error("Unsupported data type");Cb(f)}else return c(Error("node type not supported"));var t=b.mode,q;"string"===typeof a?q=N(a,{Ic:!0}).node:q=a;if(!q.sc.wc)throw new J(63);q.sc.wc(q,{mode:t&4095|q.mode&-4096,timestamp:Date.now()});var r=b.timestamp,v=b.timestamp,F=N(a,{Ic:!0}).node;F.sc.wc(F,{timestamp:Math.max(r,v)})}catch(l){return c(l)}c(null)},Kd:function(a,b){try{N(a);var c=zb(a);if(L(c.mode)){var d=
N(a,{parent:!0}).node,e=lb(a),f=xb(d,e),h=Db(d,e,!0);if(h)throw new J(h);if(!d.sc.rmdir)throw new J(63);if(f.Kc)throw new J(10);try{O.willDeletePath&&O.willDeletePath(a)}catch(v){p("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+v.message)}d.sc.rmdir(d,e);Eb(f);try{if(O.onDeletePath)O.onDeletePath(a)}catch(v){p("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+v.message)}}else if(32768===(c.mode&61440)){var m=N(a,{parent:!0}).node,t=lb(a),q=xb(m,t),r=Db(m,t,
!1);if(r)throw new J(r);if(!m.sc.unlink)throw new J(63);if(q.Kc)throw new J(10);try{O.willDeletePath&&O.willDeletePath(a)}catch(v){p("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+v.message)}m.sc.unlink(m,t);Eb(q);try{if(O.onDeletePath)O.onDeletePath(a)}catch(v){p("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+v.message)}}}catch(v){return b(v)}b(null)},Gd:function(a,b,c){a=a.get(b);a.onsuccess=function(d){c(null,d.target.result)};a.onerror=function(d){c(this.error);
d.preventDefault()}},Pd:function(a,b,c,d){a=a.put(c,b);a.onsuccess=function(){d(null)};a.onerror=function(e){d(this.error);e.preventDefault()}},Ld:function(a,b,c){a=a.delete(b);a.onsuccess=function(){c(null)};a.onerror=function(d){c(this.error);d.preventDefault()}},Jd:function(a,b,c){function d(r){if(r&&!m)return m=!0,c(r)}var e=0,f=[];Object.keys(a.entries).forEach(function(r){var v=a.entries[r],F=b.entries[r];if(!F||v.timestamp>F.timestamp)f.push(r),e++});var h=[];Object.keys(b.entries).forEach(function(r){a.entries[r]||
(h.push(r),e++)});if(!e)return c(null);var m=!1,t=("remote"===a.type?a.db:b.db).transaction([I.Dc],"readwrite"),q=t.objectStore(I.Dc);t.onerror=function(r){d(this.error);r.preventDefault()};t.oncomplete=function(){m||c(null)};f.sort().forEach(function(r){"local"===b.type?I.Gd(q,r,function(v,F){if(v)return d(v);I.Od(r,F,d)}):I.Fd(r,function(v,F){if(v)return d(v);I.Pd(q,r,F,d)})});h.sort().reverse().forEach(function(r){"local"===b.type?I.Kd(r,d):I.Ld(q,r,d)})}},Fb=null,Gb={},Hb=[],Ib=1,Jb=null,Kb=!0,
O={},J=null,wb={},Lb=0;
function N(a,b){a=mb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={nd:!0,dd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.dd)throw new J(32);a=ib(a.split("/").filter(function(h){return!!h}),!1);var e=Fb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=xb(e,a[d]);c=jb(c+"/"+a[d]);e.Kc&&(!f||f&&b.nd)&&(e=e.Kc.root);if(!f||b.Ic)for(f=0;40960===(e.mode&61440);)if(e=Mb(c),c=mb(kb(c),e),e=N(c,{dd:b.dd}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Nb(a){for(var b;;){if(a===a.parent)return a=a.zc.Rc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length}function Pb(a){var b=Ob(a.parent.id,a.name);a.Lc=Jb[b];Jb[b]=a}function Eb(a){var b=Ob(a.parent.id,a.name);if(Jb[b]===a)Jb[b]=a.Lc;else for(b=Jb[b];b;){if(b.Lc===a){b.Lc=a.Lc;break}b=b.Lc}}
function xb(a,b){var c;if(c=(c=Qb(a,"x"))?c:a.sc.lookup?0:2)throw new J(c,a);for(c=Jb[Ob(a.id,b)];c;c=c.Lc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.sc.lookup(a,b)}
function vb(a,b,c,d){Rb||(Rb=function(e,f,h,m){e||(e=this);this.parent=e;this.zc=e.zc;this.Kc=null;this.id=Ib++;this.name=f;this.mode=h;this.sc={};this.tc={};this.rdev=m},Rb.prototype={},Object.defineProperties(Rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(e){e?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(e){e?this.mode|=146:this.mode&=-147}}}));a=new Rb(a,b,c,d);Pb(a);return a}
function L(a){return 16384===(a&61440)}var Sb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Qb(a,b){if(Kb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ub(a,b){try{return xb(a,b),20}catch(c){}return Qb(a,"wx")}
function Db(a,b,c){try{var d=xb(a,b)}catch(e){return e.vc}if(a=Qb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||"/"===Nb(d))return 10}else if(L(d.mode))return 31;return 0}function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Hb[a])return a;throw new J(33);}
function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={},Object.defineProperties(Xb.prototype,{object:{get:function(){return this.node},set:function(e){this.node=e}}}));var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Hb[b]=a}var ub={open:function(a){a.tc=Gb[a.node.rdev].tc;a.tc.open&&a.tc.open(a)},Fc:function(){throw new J(70);}};function pb(a,b){Gb[a]={tc:b}}function Yb(){for(var a=[],b=[Fb.zc];b.length;){var c=b.pop();a.push(c);b.push.apply(b,c.qd)}return a}
function db(a,b){function c(h){Lb--;return b(h)}function d(h){if(h){if(!d.Wc)return d.Wc=!0,c(h)}else++f>=e.length&&c(null)}"function"===typeof a&&(b=a,a=!1);Lb++;1<Lb&&p("warning: "+Lb+" FS.syncfs operations in flight at once, probably just doing extra work");var e=Yb(),f=0;e.forEach(function(h){if(!h.type.rd)return d(null);h.type.rd(h,a,d)})}
function eb(a,b){var c="/"===b,d=!b;if(c&&Fb)throw new J(10);if(!c&&!d){var e=N(b,{nd:!1});b=e.path;e=e.node;if(e.Kc)throw new J(10);if(!L(e.mode))throw new J(54);}b={type:a,de:{},Rc:b,qd:[]};a=a.zc(b);a.zc=b;b.root=a;c?Fb=a:e&&(e.Kc=b,e.zc&&e.zc.qd.push(b))}function Zb(a,b,c){var d=N(a,{parent:!0}).node;a=lb(a);if(!a||"."===a||".."===a)throw new J(28);var e=Ub(d,a);if(e)throw new J(e);if(!d.sc.Uc)throw new J(63);return d.sc.Uc(d,a,b,c)}function H(a,b){Zb(a,(void 0!==b?b:511)&1023|16384,0)}
function $b(a,b,c){"undefined"===typeof c&&(c=b,b=438);Zb(a,b|8192,c)}function ac(a,b){if(!mb(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=lb(b);var d=Ub(c,b);if(d)throw new J(d);if(!c.sc.symlink)throw new J(63);c.sc.symlink(c,b,a)}function yb(a){a=N(a,{Ic:!0}).node;if(!a.sc.readdir)throw new J(54);return a.sc.readdir(a)}function Mb(a){a=N(a).node;if(!a)throw new J(44);if(!a.sc.readlink)throw new J(28);return mb(Nb(a.parent),a.sc.readlink(a))}
function zb(a,b){a=N(a,{Ic:!b}).node;if(!a)throw new J(44);if(!a.sc.Ac)throw new J(63);return a.sc.Ac(a)}
function Ab(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Sb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=jb(a);try{f=N(a,{Ic:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Zb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!L(f.mode))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?32:L(f.mode)&&
("r"!==Tb(b)||b&512)?31:Qb(f,Tb(b)):44))throw new J(c);if(b&512){c=f;var h;"string"===typeof c?h=N(c,{Ic:!0}).node:h=c;if(!h.sc.wc)throw new J(63);if(L(h.mode))throw new J(31);if(32768!==(h.mode&61440))throw new J(28);if(c=Qb(h,"w"))throw new J(c);h.sc.wc(h,{size:0,timestamp:Date.now()})}b&=-641;d=Wb({node:f,path:Nb(f),flags:b,seekable:!0,position:0,tc:f.tc,Ud:[],error:!1},d);d.tc.open&&d.tc.open(d);!g.logReadFiles||b&1||(bc||(bc={}),a in bc||(bc[a]=1,p("FS.trackingDelegate error on read file: "+
a)));try{O.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),O.onOpenFile(a,f))}catch(m){p("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Cb(a){if(null===a.fd)throw new J(8);a.Ec&&(a.Ec=null);try{a.tc.close&&a.tc.close(a)}catch(b){throw b;}finally{Hb[a.fd]=null}a.fd=null}
function cc(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.tc.Fc)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.tc.Fc(a,b,c);a.Ud=[];return a.position}
function Bb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(L(a.node.mode))throw new J(31);if(!a.tc.write)throw new J(28);a.flags&1024&&cc(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new J(70);b=a.tc.write(a,b,c,d,f,e);h||(a.position+=b);try{if(a.path&&O.onWriteToFile)O.onWriteToFile(a.path)}catch(m){p("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function dc(){J||(J=function(a,b){this.node=b;this.Nd=function(c){this.vc=c};this.Nd(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){wb[a]=new J(a);wb[a].stack="<generic error, no stack>"}))}var ec;function fc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function hc(a,b,c){a=jb("/dev/"+a);var d=fc(!!b,!!c);ic||(ic=64);var e=ic++<<8|0;pb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,m,t){for(var q=0,r=0;r<t;r++){try{var v=b()}catch(F){throw new J(29);}if(void 0===v&&0===q)throw new J(6);if(null===v||void 0===v)break;q++;h[m+r]=v}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,m,t){for(var q=0;q<t;q++)try{c(h[m+q])}catch(r){throw new J(29);}t&&(f.node.timestamp=Date.now());return q}});
$b(a,d,e)}var ic,P={},Rb,Xb,bc,jc={};
function kc(a,b){var c=zb;try{var d=c(a)}catch(e){if(e&&e.node&&jb(a)!==jb(Nb(e.node)))return-54;throw e;}B[b>>2]=d.dev;B[b+4>>2]=0;B[b+8>>2]=d.ino;B[b+12>>2]=d.mode;B[b+16>>2]=d.nlink;B[b+20>>2]=d.uid;B[b+24>>2]=d.gid;B[b+28>>2]=d.rdev;B[b+32>>2]=0;G=[d.size>>>0,(E=d.size,1<=+Sa(E)?0<E?(Va(+Ua(E/4294967296),4294967295)|0)>>>0:~~+Ta((E-+(~~E>>>0))/4294967296)>>>0:0)];B[b+40>>2]=G[0];B[b+44>>2]=G[1];B[b+48>>2]=4096;B[b+52>>2]=d.blocks;B[b+56>>2]=d.atime.getTime()/1E3|0;B[b+60>>2]=0;B[b+64>>2]=d.mtime.getTime()/
1E3|0;B[b+68>>2]=0;B[b+72>>2]=d.ctime.getTime()/1E3|0;B[b+76>>2]=0;G=[d.ino>>>0,(E=d.ino,1<=+Sa(E)?0<E?(Va(+Ua(E/4294967296),4294967295)|0)>>>0:~~+Ta((E-+(~~E>>>0))/4294967296)>>>0:0)];B[b+80>>2]=G[0];B[b+84>>2]=G[1];return 0}var Q=0;function R(){Q+=4;return B[Q-4>>2]}function T(a){void 0===a&&(a=R());a=Hb[a];if(!a)throw new J(8);return a}function lc(){n()}var mc=ia||"undefined"!==typeof dateNow||1,nc=0,oc=0,U=0,pc=0,qc=0,rc=null,sc=null,tc=!1;
function uc(){for(var a=vc.length-1;0<=a;--a)wc(a);vc=[];xc=[]}var xc=[];function yc(){if(zc&&Ac.Tc)for(var a=0;a<xc.length;++a){var b=xc[a];xc.splice(a,1);--a;b.ie.apply(this,b.Wd)}}var zc=0,Ac=null,vc=[];function wc(a){var b=vc[a];b.target.removeEventListener(b.Cc,b.wd,b.Gc);vc.splice(a,1)}
function Bc(a){function b(d){++zc;Ac=a;yc();a.Jc(d);yc();--zc}if(a.Hc)a.wd=b,a.target.addEventListener(a.Cc,b,a.Gc),vc.push(a),tc||(Pa.push(uc),tc=!0);else for(var c=0;c<vc.length;++c)vc[c].target==a.target&&vc[c].Cc==a.Cc&&wc(c--)}function Cc(a){return a===a+0?A(a):a}var Dc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Ec(a){return Dc[a]||("undefined"!==typeof document?document.querySelector(Cc(a)):void 0)}var Fc=0;
function Gc(a,b,c,d){a|=0;b|=0;c|=0;d|=0;var e=0;Fc=Fc+1|0;for(B[a>>2]=Fc;(e|0)<(d|0);){if(0==(B[c+(e<<3)>>2]|0))return B[c+(e<<3)>>2]=Fc,B[c+((e<<3)+4)>>2]=b,B[c+((e<<3)+8)>>2]=0,ra=d|0,c|0;e=e+1|0}d=2*d|0;c=Hc(c|0,8*(d+1|0)|0)|0;c=Gc(a|0,b|0,c|0,d|0)|0;ra=d|0;return c|0}
function Ic(a,b,c,d,e,f){nc||(nc=M(164));a={target:Ec(a),Tc:!0,Cc:f,Hc:d,Jc:function(h){h=h||event;var m=nc;u(h.key?h.key:"",w,m+0,32);u(h.code?h.code:"",w,m+32,32);B[m+64>>2]=h.location;B[m+68>>2]=h.ctrlKey;B[m+72>>2]=h.shiftKey;B[m+76>>2]=h.altKey;B[m+80>>2]=h.metaKey;B[m+84>>2]=h.repeat;u(h.locale?h.locale:"",w,m+88,32);u(h.char?h.char:"",w,m+120,32);B[m+152>>2]=h.charCode;B[m+156>>2]=h.keyCode;B[m+160>>2]=h.which;Jc(d,e,m,b)&&h.preventDefault()},Gc:c};Bc(a)}
function Kc(a,b,c){B[a>>2]=b.screenX;B[a+4>>2]=b.screenY;B[a+8>>2]=b.clientX;B[a+12>>2]=b.clientY;B[a+16>>2]=b.ctrlKey;B[a+20>>2]=b.shiftKey;B[a+24>>2]=b.altKey;B[a+28>>2]=b.metaKey;Ga[a+32>>1]=b.button;Ga[a+34>>1]=b.buttons;var d=b.movementY||b.screenY-sc;B[a+36>>2]=b.movementX||b.screenX-rc;B[a+40>>2]=d;c=0>Dc.indexOf(c)?c.getBoundingClientRect():{left:0,top:0};B[a+44>>2]=b.clientX-c.left;B[a+48>>2]=b.clientY-c.top;"wheel"!==b.type&&"mousewheel"!==b.type&&(rc=b.screenX,sc=b.screenY)}
function Lc(a,b,c,d,e,f){oc||(oc=M(64));a=Ec(a);Bc({target:a,Tc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Cc:f,Hc:d,Jc:function(h){h=h||event;Kc(oc,h,a);Jc(d,e,oc,b)&&h.preventDefault()},Gc:c})}
function Mc(a,b,c,d){pc||(pc=M(36));a=Ec(a);Bc({target:a,Cc:"resize",Hc:d,Jc:function(e){e=e||event;if(e.target==a){var f=pc,h=document.body;B[f>>2]=e.detail;B[f+4>>2]=h.clientWidth;B[f+8>>2]=h.clientHeight;B[f+12>>2]=innerWidth;B[f+16>>2]=innerHeight;B[f+20>>2]=outerWidth;B[f+24>>2]=outerHeight;B[f+28>>2]=pageXOffset;B[f+32>>2]=pageYOffset;Jc(d,10,f,b)&&e.preventDefault()}},Gc:c})}
function Nc(a,b,c,d,e,f){qc||(qc=M(1684));a=Ec(a);Bc({target:a,Tc:"touchstart"==f||"touchend"==f,Cc:f,Hc:d,Jc:function(h){h=h||event;for(var m={},t=0;t<h.touches.length;++t){var q=h.touches[t];q.hd=!1;m[q.identifier]=q}for(t=0;t<h.changedTouches.length;++t)q=h.changedTouches[t],m[q.identifier]=q,q.hd=!0;for(t=0;t<h.targetTouches.length;++t)q=h.targetTouches[t],m[q.identifier].Id=!0;var r=q=qc;B[r+4>>2]=h.ctrlKey;B[r+8>>2]=h.shiftKey;B[r+12>>2]=h.altKey;B[r+16>>2]=h.metaKey;r+=20;var v=a.getBoundingClientRect(),
F=0;for(t in m){var l=m[t];B[r>>2]=l.identifier;B[r+4>>2]=l.screenX;B[r+8>>2]=l.screenY;B[r+12>>2]=l.clientX;B[r+16>>2]=l.clientY;B[r+20>>2]=l.pageX;B[r+24>>2]=l.pageY;B[r+28>>2]=l.hd;B[r+32>>2]=l.Id;B[r+36>>2]=l.clientX-v.left;B[r+40>>2]=l.clientY-v.top;r+=52;if(32<=++F)break}B[q>>2]=F;Jc(d,e,q,b)&&h.preventDefault()},Gc:c})}function Oc(a,b,c,d,e,f){a={target:Ec(a),Cc:f,Hc:d,Jc:function(h){h=h||event;Jc(d,e,0,b)&&h.preventDefault()},Gc:c};Bc(a)}
function Pc(a,b,c,d,e){function f(m){m=m||event;Kc(U,m,a);D[U+64>>3]=m.wheelDeltaX||0;D[U+72>>3]=-(m.wheelDeltaY||m.wheelDelta);D[U+80>>3]=0;B[U+88>>2]=0;Jc(d,9,U,b)&&m.preventDefault()}function h(m){m=m||event;var t=U;Kc(t,m,a);D[t+64>>3]=m.deltaX;D[t+72>>3]=m.deltaY;D[t+80>>3]=m.deltaZ;B[t+88>>2]=m.deltaMode;Jc(d,9,t,b)&&m.preventDefault()}U||(U=M(96));Bc({target:a,Tc:!0,Cc:e,Hc:d,Jc:"wheel"==e?h:f,Gc:c})}
function Qc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Rc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Sc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Tc=1,Uc=0,Vc=[],V=[],Xc=[],Yc=[],Zc=[],W=[],X=[],ad={},bd=null,cd={},dd={};
function Y(a){Uc||(Uc=a)}function ed(a){for(var b=Tc++,c=a.length;c<b;c++)a[c]=null;return b}var fd=[0];
function gd(a){a||(a=bd);if(!a.Dd){a.Dd=!0;var b=a.$c;2>a.version&&(Qc(b),Rc(b),Sc(b));b.Yd=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var hd,id,jd=["default","low-power","high-performance"],kd={};function ld(){if(!md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in kd)a[b]=kd[b];var c=[];for(b in a)c.push(b+"="+a[b]);md=c}return md}var md;
function nd(a,b,c,d){for(var e=0;e<a;e++){var f=Z[c](),h=f&&ed(d);f?(f.name=h,d[h]=f):Y(1282);B[b+4*e>>2]=h}}
function od(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)B[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Y(1280);p("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Y(1280);p("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}B[b>>2]=c}else Y(1281)}function pd(a){var b=Ea(a)+1,c=M(b);u(a,w,c,b);return c}
function qd(a,b,c,d,e){a-=5120;a=1==a?w:4==a?B:6==a?C:5==a||28922==a?Ia:Ha;var f=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+4-1&-4)>>f)}function rd(a){return 0===a%4&&(0!==a%100||0===a%400)}function sd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var td=[31,29,31,30,31,30,31,31,30,31,30,31],ud=[31,28,31,30,31,30,31,31,30,31,30,31];
function vd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(rd(a.getFullYear())?td:ud)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function wd(a,b,c,d){function e(l,x,z){for(l="number"===typeof l?l.toString():l||"";l.length<x;)l=z[0]+l;return l}function f(l,x){return e(l,x,"0")}function h(l,x){function z($c){return 0>$c?-1:0<$c?1:0}var S;0===(S=z(l.getFullYear()-x.getFullYear()))&&0===(S=z(l.getMonth()-x.getMonth()))&&(S=z(l.getDate()-x.getDate()));return S}function m(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function t(l){l=vd(new Date(l.xc+1900,0,1),l.Zc);var x=new Date(l.getFullYear()+1,0,4),z=m(new Date(l.getFullYear(),0,4));x=m(x);return 0>=h(z,l)?0>=h(x,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var q=B[d+40>>2];d={Sd:B[d>>2],Rd:B[d+4>>2],Xc:B[d+8>>2],Sc:B[d+12>>2],Nc:B[d+16>>2],xc:B[d+20>>2],Yc:B[d+24>>2],Zc:B[d+28>>2],ke:B[d+32>>2],Qd:B[d+
36>>2],Td:q?A(q):""};c=A(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
F="January February March April May June July August September October November December".split(" ");q={"%a":function(l){return v[l.Yc].substring(0,3)},"%A":function(l){return v[l.Yc]},"%b":function(l){return F[l.Nc].substring(0,3)},"%B":function(l){return F[l.Nc]},"%C":function(l){return f((l.xc+1900)/100|0,2)},"%d":function(l){return f(l.Sc,2)},"%e":function(l){return e(l.Sc,2," ")},"%g":function(l){return t(l).toString().substring(2)},"%G":function(l){return t(l)},"%H":function(l){return f(l.Xc,
2)},"%I":function(l){l=l.Xc;0==l?l=12:12<l&&(l-=12);return f(l,2)},"%j":function(l){return f(l.Sc+sd(rd(l.xc+1900)?td:ud,l.Nc-1),3)},"%m":function(l){return f(l.Nc+1,2)},"%M":function(l){return f(l.Rd,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.Xc&&12>l.Xc?"AM":"PM"},"%S":function(l){return f(l.Sd,2)},"%t":function(){return"\t"},"%u":function(l){return l.Yc||7},"%U":function(l){var x=new Date(l.xc+1900,0,1),z=0===x.getDay()?x:vd(x,7-x.getDay());l=new Date(l.xc+1900,l.Nc,l.Sc);return 0>
h(z,l)?f(Math.ceil((31-z.getDate()+(sd(rd(l.getFullYear())?td:ud,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(z,x)?"01":"00"},"%V":function(l){var x=new Date(l.xc+1901,0,4),z=m(new Date(l.xc+1900,0,4));x=m(x);var S=vd(new Date(l.xc+1900,0,1),l.Zc);return 0>h(S,z)?"53":0>=h(x,S)?"01":f(Math.ceil((z.getFullYear()<l.xc+1900?l.Zc+32-z.getDate():l.Zc+1-z.getDate())/7),2)},"%w":function(l){return l.Yc},"%W":function(l){var x=new Date(l.xc,0,1),z=1===x.getDay()?x:vd(x,0===x.getDay()?1:7-x.getDay()+1);l=
new Date(l.xc+1900,l.Nc,l.Sc);return 0>h(z,l)?f(Math.ceil((31-z.getDate()+(sd(rd(l.getFullYear())?td:ud,l.getMonth()-1)-31)+l.getDate())/7),2):0===h(z,x)?"01":"00"},"%y":function(l){return(l.xc+1900).toString().substring(2)},"%Y":function(l){return l.xc+1900},"%z":function(l){l=l.Qd;var x=0<=l;l=Math.abs(l)/60;return(x?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Td},"%%":function(){return"%"}};for(r in q)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));r=
rb(c,!1);if(r.length>b)return 0;y.set(r,a);return r.length-1}var xd;dc();Jb=Array(4096);eb(K,"/");H("/tmp");H("/home");H("/home/web_user");
(function(){H("/dev");pb(259,{read:function(){return 0},write:function(d,e,f,h){return h}});$b("/dev/null",259);ob(1280,sb);ob(1536,tb);$b("/dev/tty",1280);$b("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ia)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){n("random_device")});hc("random",b);hc("urandom",b);H("/dev/shm");
H("/dev/shm/tmp")})();H("/proc");H("/proc/self");H("/proc/self/fd");eb({zc:function(){var a=vb("/proc/self","fd",16895,73);a.sc={lookup:function(b,c){var d=Hb[+c];if(!d)throw new J(8);b={parent:null,zc:{Rc:"fake"},sc:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");ia?lc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?lc=dateNow:lc=function(){return performance.now()};
for(var Z,yd=new Float32Array(256),zd=0;256>zd;zd++)fd[zd]=yd.subarray(0,zd+1);for(zd=0;256>zd;zd++);function rb(a,b){var c=Array(Ea(a)+1);a=u(a,c,0,c.length);b&&(c.length=a);return c}
var Jd={ga:function(){},ib:function(){hb(63);return-1},ha:function(a,b){Q=b;try{var c=A(R()),d=R();return kc(c,d)}catch(e){return"undefined"!==typeof P&&e instanceof J||n(e),-e.vc}},sb:function(a,b){Q=b;try{var c=T(),d=R();return kc(c.path,d)}catch(e){return"undefined"!==typeof P&&e instanceof J||n(e),-e.vc}},rb:function(a,b){Q=b;try{var c=T(),d=R(),e=R();c.Ec||(c.Ec=yb(c.path));a=0;for(var f=cc(c,0,1),h=Math.floor(f/280);h<c.Ec.length&&a+280<=e;){var m=c.Ec[h];if("."===m[0]){var t=1;var q=4}else{var r=
xb(c.node,m);t=r.id;q=8192===(r.mode&61440)?2:L(r.mode)?4:40960===(r.mode&61440)?10:8}G=[t>>>0,(E=t,1<=+Sa(E)?0<E?(Va(+Ua(E/4294967296),4294967295)|0)>>>0:~~+Ta((E-+(~~E>>>0))/4294967296)>>>0:0)];B[d+a>>2]=G[0];B[d+a+4>>2]=G[1];G=[280*(h+1)>>>0,(E=280*(h+1),1<=+Sa(E)?0<E?(Va(+Ua(E/4294967296),4294967295)|0)>>>0:~~+Ta((E-+(~~E>>>0))/4294967296)>>>0:0)];B[d+a+8>>2]=G[0];B[d+a+12>>2]=G[1];Ga[d+a+16>>1]=280;y[d+a+18>>0]=q;u(m,w,d+a+19,256);a+=280;h+=1}cc(c,280*h,0);return a}catch(v){return"undefined"!==
typeof P&&v instanceof J||n(v),-v.vc}},fa:function(a,b){Q=b;try{var c=T();switch(R()){case 0:var d=R();return 0>d?-28:Ab(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=R(),c.flags|=d,0;case 12:return d=R(),Ga[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return hb(28),-1;default:return-28}}catch(e){return"undefined"!==typeof P&&e instanceof J||n(e),-e.vc}},H:function(a,b){Q=b;try{var c=A(R()),d=R(),e=R();return Ab(c,d,e).fd}catch(f){return"undefined"!==
typeof P&&f instanceof J||n(f),-f.vc}},qb:function(a,b){Q=b;try{var c=T(),d=R();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=R();return B[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=R();if(!c.tc.Ed)throw new J(59);return c.tc.Ed(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:n("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof P&&
f instanceof J||n(f),-f.vc}},nb:function(a,b){Q=b;try{var c=A(R()),d=R();var e=R();if(0>=e)var f=-28;else{var h=Mb(c),m=Math.min(e,Ea(h)),t=y[d+m];u(h,w,d,e+1);y[d+m]=t;f=m}return f}catch(q){return"undefined"!==typeof P&&q instanceof J||n(q),-q.vc}},hb:function(a,b){Q=b;try{var c=R(),d=R();if(-1===c||0===d)var e=-28;else{var f=jc[c];if(f&&d===f.ae){var h=Hb[f.fd],m=f.flags,t=f.offset,q=new Uint8Array(w.subarray(c,c+d));h&&h.tc.Vc&&h.tc.Vc(h,q,t,d,m);jc[c]=null;f.ud&&Ad(f.be)}e=0}return e}catch(r){return"undefined"!==
typeof P&&r instanceof J||n(r),-r.vc}},r:function(){},a:function(){n()},lb:function(a,b){if(0===a)a=Date.now();else if(1===a&&mc)a=lc();else return hb(28),-1;B[b>>2]=a/1E3|0;B[b+4>>2]=a%1E3*1E6|0;return 0},Ab:function(){console.log("fs.h: registering Module['ccall']");g.ccall=ya},Ib:function(a){var b=A(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var d=new Uint8Array(c.response);ya("emsc_load_data","int",["string","array","number"],[b,d,d.length])};c.send()},
da:function(a,b,c){xd||(xd=[]);var d=xd;d.length=0;for(var e;e=w[b++];)100===e||102===e?(c=c+7&-8,d.push(D[c>>3]),c+=8):(c=c+3&-4,d.push(B[c>>2]),c+=4);return fb[a].apply(null,d)},ca:function(){return devicePixelRatio||1},ea:function(a,b,c){a=Ec(a);if(!a)return-4;a=a.getBoundingClientRect();D[b>>3]=a.width;D[c>>3]=a.height;return 0},m:function(a,b){Bd(a,b||1);throw"longjmp";},cb:function(a,b,c){w.set(w.subarray(b,b+c),a)},Ia:function(a,b){function c(d){Cd(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
db:function(a){var b=y.length;if(2147418112<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ua.grow(Math.min(2147418112,d)-buffer.byteLength+65535>>16);Ja(ua.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ba:function(a,b,c){a=Ec(a);if(!a)return-4;a.width=b;a.height=c;return 0},Sa:function(a,b,c,d){Ic(a,b,c,d,2,"keydown");return 0},Qa:function(a,b,c,d){Ic(a,b,c,d,1,"keypress");return 0},Ra:function(a,
b,c,d){Ic(a,b,c,d,3,"keyup");return 0},Ya:function(a,b,c,d){Lc(a,b,c,d,5,"mousedown");return 0},Va:function(a,b,c,d){Lc(a,b,c,d,33,"mouseenter");return 0},Ua:function(a,b,c,d){Lc(a,b,c,d,34,"mouseleave");return 0},Wa:function(a,b,c,d){Lc(a,b,c,d,8,"mousemove");return 0},Xa:function(a,b,c,d){Lc(a,b,c,d,6,"mouseup");return 0},eb:function(a,b,c,d){Mc(a,b,c,d);return 0},La:function(a,b,c,d){Nc(a,b,c,d,25,"touchcancel");return 0},Ma:function(a,b,c,d){Nc(a,b,c,d,23,"touchend");return 0},Na:function(a,b,
c,d){Nc(a,b,c,d,24,"touchmove");return 0},Oa:function(a,b,c,d){Nc(a,b,c,d,22,"touchstart");return 0},Ka:function(a,b,c,d){Oc(a,b,c,d,31,"webglcontextlost");return 0},Ja:function(a,b,c,d){Oc(a,b,c,d,32,"webglcontextrestored");return 0},Ta:function(a,b,c,d){a=Ec(a);return"undefined"!==typeof a.onwheel?(Pc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Pc(a,b,c,d,"mousewheel"),0):-1},aa:function(a,b){var c={};b>>=2;c.alpha=!!B[b];c.depth=!!B[b+1];c.stencil=!!B[b+2];c.antialias=!!B[b+3];c.premultipliedAlpha=
!!B[b+4];c.preserveDrawingBuffer=!!B[b+5];c.powerPreference=jd[B[b+6]];c.failIfMajorPerformanceCaveat=!!B[b+7];c.Hd=B[b+8];c.ce=B[b+9];c.ld=B[b+10];c.xd=B[b+11];c.ee=B[b+12];c.ge=B[b+13];a=Ec(a);if(!a||c.xd)c=0;else if(a=a.getContext("webgl",c)){b=M(8);var d={$d:b,attributes:c,version:c.Hd,$c:a};a.canvas&&(a.canvas.Vd=d);ad[b]=d;("undefined"===typeof c.ld||c.ld)&&gd(d);c=b}else c=0;return c},Za:function(a,b){a=ad[a];b=A(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?Qc(Z):"OES_vertex_array_object"==
b?Rc(Z):"WEBGL_draw_buffers"==b&&Sc(Z);return!!a.$c.getExtension(b)},ab:function(a){a>>=2;for(var b=0;14>b;++b)B[a+b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},$a:function(a){bd=ad[a];g.Xd=Z=bd&&bd.$c;return!a||Z?0:-5},jb:function(a,b){var c=0;ld().forEach(function(d,e){var f=b+c;e=B[a+4*e>>2]=f;for(f=0;f<d.length;++f)y[e++>>0]=d.charCodeAt(f);y[e>>0]=0;c+=d.length+1});return 0},kb:function(a,b){var c=ld();B[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B[b>>2]=d;return 0},_a:function(a){Dd(a)},
n:function(a){try{var b=T(a);Cb(b);return 0}catch(c){return"undefined"!==typeof P&&c instanceof J||n(c),c.vc}},mb:function(a,b){try{var c=T(a);y[b>>0]=c.tty?2:L(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof P&&d instanceof J||n(d),d.vc}},pb:function(a,b,c,d){try{a:{for(var e=T(a),f=a=0;f<c;f++){var h=B[b+(8*f+4)>>2],m=e,t=B[b+8*f>>2],q=h,r=void 0,v=y;if(0>q||0>r)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(L(m.node.mode))throw new J(31);
if(!m.tc.read)throw new J(28);var F="undefined"!==typeof r;if(!F)r=m.position;else if(!m.seekable)throw new J(70);var l=m.tc.read(m,v,t,q,r);F||(m.position+=l);var x=l;if(0>x){var z=-1;break a}a+=x;if(x<h)break}z=a}B[d>>2]=z;return 0}catch(S){return"undefined"!==typeof P&&S instanceof J||n(S),S.vc}},bb:function(a,b,c,d,e){try{var f=T(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;cc(f,a,d);G=[f.position>>>0,(E=f.position,1<=+Sa(E)?0<E?(Va(+Ua(E/4294967296),4294967295)|
0)>>>0:~~+Ta((E-+(~~E>>>0))/4294967296)>>>0:0)];B[e>>2]=G[0];B[e+4>>2]=G[1];f.Ec&&0===a&&0===d&&(f.Ec=null);return 0}catch(h){return"undefined"!==typeof P&&h instanceof J||n(h),h.vc}},ob:function(a,b,c,d){try{a:{for(var e=T(a),f=a=0;f<c;f++){var h=Bb(e,y,B[b+8*f>>2],B[b+(8*f+4)>>2]);if(0>h){var m=-1;break a}a+=h}m=a}B[d>>2]=m;return 0}catch(t){return"undefined"!==typeof P&&t instanceof J||n(t),t.vc}},s:function(){return ra|0},i:function(a){Z.activeTexture(a)},V:function(a,b){Z.attachShader(V[a],X[b])},
c:function(a,b){Z.bindBuffer(a,Vc[b])},h:function(a,b){Z.bindFramebuffer(a,Xc[b])},Da:function(a,b){Z.bindRenderbuffer(a,Yc[b])},b:function(a,b){Z.bindTexture(a,Zc[b])},N:function(a,b,c,d){Z.blendColor(a,b,c,d)},O:function(a,b){Z.blendEquationSeparate(a,b)},P:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Y:function(a,b,c,d){Z.bufferData(a,c?w.subarray(c,c+b):b,d)},u:function(a,b,c,d){Z.bufferSubData(a,b,w.subarray(d,d+c))},p:function(a){return Z.checkFramebufferStatus(a)},sa:function(a){Z.clear(a)},
wa:function(a,b,c,d){Z.clearColor(a,b,c,d)},va:function(a){Z.clearDepth(a)},ua:function(a){Z.clearStencil(a)},D:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},vb:function(a){Z.compileShader(X[a])},X:function(a,b,c,d,e,f,h,m){Z.compressedTexImage2D(a,b,c,d,e,f,m?w.subarray(m,m+h):null)},Aa:function(){var a=ed(V),b=Z.createProgram();b.name=a;V[a]=b;return a},xb:function(a){var b=ed(X);X[b]=Z.createShader(a);return b},M:function(a){Z.cullFace(a)},Fa:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>
2],e=Vc[d];e&&(Z.deleteBuffer(e),e.name=0,Vc[d]=null,d==hd&&(hd=0),d==id&&(id=0))}},e:function(a,b){for(var c=0;c<a;++c){var d=B[b+4*c>>2],e=Xc[d];e&&(Z.deleteFramebuffer(e),e.name=0,Xc[d]=null)}},_:function(a){if(a){var b=V[a];b?(Z.deleteProgram(b),b.name=0,V[a]=null,cd[a]=null):Y(1281)}},v:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=Yc[d];e&&(Z.deleteRenderbuffer(e),e.name=0,Yc[d]=null)}},E:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},$:function(a,b){for(var c=
0;c<a;c++){var d=B[b+4*c>>2],e=Zc[d];e&&(Z.deleteTexture(e),e.name=0,Zc[d]=null)}},B:function(a){Z.depthFunc(a)},C:function(a){Z.depthMask(!!a)},f:function(a){Z.disable(a)},I:function(a){Z.disableVertexAttribArray(a)},Fb:function(a,b,c){Z.drawArrays(a,b,c)},Gb:function(a,b,c,d){Z.drawElements(a,b,c,d)},g:function(a){Z.enable(a)},oa:function(a){Z.enableVertexAttribArray(a)},l:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,Yc[d])},d:function(a,b,c,d,e){Z.framebufferTexture2D(a,b,c,Zc[d],e)},L:function(a){Z.frontFace(a)},
Z:function(a,b){nd(a,b,"createBuffer",Vc)},q:function(a,b){nd(a,b,"createFramebuffer",Xc)},Ea:function(a,b){nd(a,b,"createRenderbuffer",Yc)},Ba:function(a,b){nd(a,b,"createTexture",Zc)},xa:function(a,b){return Z.getAttribLocation(V[a],A(b))},k:function(a,b){od(a,b)},ya:function(a,b,c,d){a=Z.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?u(a,w,d,b):0;c&&(B[c>>2]=b)},U:function(a,b,c){if(c)if(a>=Tc)Y(1281);else{var d=cd[a];if(d)if(35716==b)a=Z.getProgramInfoLog(V[a]),null===a&&(a=
"(unknown error)"),B[c>>2]=a.length+1;else if(35719==b)B[c>>2]=d.bd;else if(35722==b){if(-1==d.Pc){a=V[a];var e=Z.getProgramParameter(a,35721);for(b=d.Pc=0;b<e;++b)d.Pc=Math.max(d.Pc,Z.getActiveAttrib(a,b).name.length+1)}B[c>>2]=d.Pc}else if(35381==b){if(-1==d.Qc)for(a=V[a],e=Z.getProgramParameter(a,35382),b=d.Qc=0;b<e;++b)d.Qc=Math.max(d.Qc,Z.getActiveUniformBlockName(a,b).length+1);B[c>>2]=d.Qc}else B[c>>2]=Z.getProgramParameter(V[a],b);else Y(1282)}else Y(1281)},ub:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);
null===a&&(a="(unknown error)");b=0<b&&d?u(a,w,d,b):0;c&&(B[c>>2]=b)},ja:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(X[a]),B[c>>2]=null===a||0==a.length?0:a.length+1):B[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Ga:function(a){if(dd[a])return dd[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=pd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
Z.getParameter(a))||Y(1280);b=pd(b);break;case 7938:b=pd("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=pd(b);break;default:return Y(1280),0}return dd[a]=b},t:function(a,b){b=A(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=cd[a]&&cd[a].sd[b])&&
0<=c&&c<a[0]?a[1]+c:-1},za:function(a){Z.linkProgram(V[a]);var b=V[a];a=cd[a]={sd:{},bd:0,Pc:-1,Qc:-1};for(var c=a.sd,d=Z.getProgramParameter(b,35718),e=0;e<d;++e){var f=Z.getActiveUniform(b,e),h=f.name;a.bd=Math.max(a.bd,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=Z.getUniformLocation(b,h);if(m){var t=ed(W);c[h]=[f.size,t];W[t]=m;for(var q=1;q<f.size;++q)m=Z.getUniformLocation(b,h+"["+q+"]"),t=ed(W),W[t]=m}}},K:function(a,b){Z.polygonOffset(a,b)},Ca:function(a,b,c,d){Z.renderbufferStorage(a,
b,c,d)},S:function(a,b,c,d){Z.scissor(a,b,c,d)},wb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?B[d+4*f>>2]:-1;e+=A(B[c+4*f>>2],0>h?void 0:h)}Z.shaderSource(X[a],e)},zb:function(a,b,c){Z.stencilFunc(a,b,c)},R:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},A:function(a){Z.stencilMask(a)},yb:function(a,b,c){Z.stencilOp(a,b,c)},Q:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},W:function(a,b,c,d,e,f,h,m,t){Z.texImage2D(a,b,c,d,e,f,h,m,t?qd(m,h,d,e,t):null)},j:function(a,b,c){Z.texParameteri(a,
b,c)},o:function(a,b,c,d,e,f,h,m,t){var q=null;t&&(q=qd(m,h,e,f,t));Z.texSubImage2D(a,b,c,d,e,f,h,m,q)},na:function(a,b,c){if(256>=b)for(var d=fd[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);Z.uniform1fv(W[a],d)},J:function(a,b){Z.uniform1i(W[a],b)},ma:function(a,b,c){if(256>=2*b)for(var d=fd[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);Z.uniform2fv(W[a],d)},la:function(a,b,c){if(256>=3*b)for(var d=fd[3*b-1],e=0;e<3*b;e+=3)d[e]=
C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);Z.uniform3fv(W[a],d)},ka:function(a,b,c){if(256>=4*b)for(var d=fd[4*b-1],e=0;e<4*b;e+=4)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2],d[e+3]=C[c+(4*e+12)>>2];else d=C.subarray(c>>2,c+16*b>>2);Z.uniform4fv(W[a],d)},Hb:function(a,b,c,d){if(256>=16*b)for(var e=fd[16*b-1],f=0;f<16*b;f+=16)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>
2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2],e[f+9]=C[d+(4*f+36)>>2],e[f+10]=C[d+(4*f+40)>>2],e[f+11]=C[d+(4*f+44)>>2],e[f+12]=C[d+(4*f+48)>>2],e[f+13]=C[d+(4*f+52)>>2],e[f+14]=C[d+(4*f+56)>>2],e[f+15]=C[d+(4*f+60)>>2];else e=C.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(W[a],!!c,e)},qa:function(a){Z.useProgram(V[a])},fb:function(a,b){Z.vertexAttribDivisor(a,b)},pa:function(a,b,c,d,e,f){Z.vertexAttribPointer(a,b,c,!!d,e,f)},T:function(a,b,c,d){Z.viewport(a,
b,c,d)},ta:Ed,Pa:Fd,memory:ua,y:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Gd()});document.body.append(a)},x:function(){document.getElementById("_sokol_app_input_element").focus()},Ha:function(){window.addEventListener("beforeunload",function(a){0!=Hd()&&(a.preventDefault(),a.returnValue=" ")})},tb:function(a){window.addEventListener("paste",function(b){b=b.clipboardData.getData("text");
ya("_sapp_emsc_onpaste","void",["string"],[b])});window.addEventListener("keyup",function(b){if(b.ctrlKey&&"c"==b.key){console.log("copying",A(a));b=A(a);var c=document.createElement("textarea");c.setAttribute("autocomplete","off");c.setAttribute("autocorrect","off");c.setAttribute("autocapitalize","off");c.setAttribute("spellcheck","false");c.style.left="-100px";c.style.top="-100px";c.style.height=1;c.style.width=1;c.value=b;document.body.appendChild(c);c.select();document.execCommand("copy");document.body.removeChild(c)}})},
w:function(){document.getElementById("_sokol_app_input_element").blur()},Bb:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())ya("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},Cb:function(){return g.Oc?g.Oc.bufferSize:0},Eb:function(a,b,c){g.yc=null;g.Oc=null;"undefined"!==typeof AudioContext?(g.yc=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):"undefined"!==
typeof webkitAudioContext?(g.yc=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(g.yc=null,console.log("sokol_audio.h: no WebAudio support"));return g.yc?(console.log("sokol_audio.h: sample rate ",g.yc.sampleRate),g.Oc=g.yc.createScriptProcessor(c,0,b),g.Oc.onaudioprocess=function(d){var e=d.outputBuffer.length,f=Id(e);if(f)for(var h=d.outputBuffer.numberOfChannels,m=0;m<h;m++)for(var t=d.outputBuffer.getChannelData(m),q=0;q<
e;q++)t[q]=C[(f>>2)+(h*q+m)]},g.Oc.connect(g.yc.destination),a=function(){g.yc&&"suspended"===g.yc.state&&g.yc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Db:function(){return g.yc?g.yc.sampleRate:0},ra:Gc,F:function(a){ra=a|0},ia:function(){return navigator.userAgent.includes("Macintosh")?1:0},z:function(){return performance.now()},gb:function(a,b,c,d){return wd(a,b,c,d)},Jb:function(){hb(6);
return-1},table:va,G:function(a,b,c){a|=0;b|=0;c|=0;for(var d=0,e;(d|0)<(c|0);){e=B[b+(d<<3)>>2]|0;if(0==(e|0))break;if((e|0)==(a|0))return B[b+((d<<3)+4)>>2]|0;d=d+1|0}return 0}},Kd=function(){function a(e){g.asm=e.exports;Wa--;g.monitorRunDependencies&&g.monitorRunDependencies(Wa);0==Wa&&(null!==Xa&&(clearInterval(Xa),Xa=null),Ya&&(e=Ya,Ya=null,e()))}function b(e){a(e.instance)}function c(e){return cb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){p("failed to asynchronously prepare wasm: "+
f);n(f)})}var d={a:Jd};Wa++;g.monitorRunDependencies&&g.monitorRunDependencies(Wa);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return p("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(sa||"function"!==typeof WebAssembly.instantiateStreaming||Za()||"function"!==typeof fetch)return c(b);fetch($a,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){p("wasm streaming compile failed: "+f);p("falling back to ArrayBuffer instantiation");
c(b)})})})();return{}}();g.asm=Kd;var gb=g.___wasm_call_ctors=function(){return(gb=g.___wasm_call_ctors=g.asm.Kb).apply(null,arguments)},Ad=g._free=function(){return(Ad=g._free=g.asm.Lb).apply(null,arguments)},M=g._malloc=function(){return(M=g._malloc=g.asm.Mb).apply(null,arguments)};g._emsc_load_data=function(){return(g._emsc_load_data=g.asm.Nb).apply(null,arguments)};g.___em_js__emsc_fs_init=function(){return(g.___em_js__emsc_fs_init=g.asm.Ob).apply(null,arguments)};
g.___em_js__emsc_load_file=function(){return(g.___em_js__emsc_load_file=g.asm.Pb).apply(null,arguments)};var Gd=g.__sapp_emsc_notify_keyboard_hidden=function(){return(Gd=g.__sapp_emsc_notify_keyboard_hidden=g.asm.Qb).apply(null,arguments)};g.___em_js__sapp_js_create_textfield=function(){return(g.___em_js__sapp_js_create_textfield=g.asm.Rb).apply(null,arguments)};g.___em_js__sapp_js_focus_textfield=function(){return(g.___em_js__sapp_js_focus_textfield=g.asm.Sb).apply(null,arguments)};
g.___em_js__sapp_js_unfocus_textfield=function(){return(g.___em_js__sapp_js_unfocus_textfield=g.asm.Tb).apply(null,arguments)};g.__sapp_emsc_onpaste=function(){return(g.__sapp_emsc_onpaste=g.asm.Ub).apply(null,arguments)};var Hd=g.__sapp_html5_get_ask_leave_site=function(){return(Hd=g.__sapp_html5_get_ask_leave_site=g.asm.Vb).apply(null,arguments)};g.___em_js__sapp_js_hook_beforeunload=function(){return(g.___em_js__sapp_js_hook_beforeunload=g.asm.Wb).apply(null,arguments)};
g.___em_js__sapp_js_write_clipboard=function(){return(g.___em_js__sapp_js_write_clipboard=g.asm.Xb).apply(null,arguments)};g.___em_js__sapp_js_init_clipboard=function(){return(g.___em_js__sapp_js_init_clipboard=g.asm.Yb).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Zb).apply(null,arguments)};g.___em_js__stm_js_perfnow=function(){return(g.___em_js__stm_js_perfnow=g.asm._b).apply(null,arguments)};
var Id=g.__saudio_emsc_pull=function(){return(Id=g.__saudio_emsc_pull=g.asm.$b).apply(null,arguments)};g.___em_js__saudio_js_init=function(){return(g.___em_js__saudio_js_init=g.asm.ac).apply(null,arguments)};g.___em_js__saudio_js_sample_rate=function(){return(g.___em_js__saudio_js_sample_rate=g.asm.bc).apply(null,arguments)};g.___em_js__saudio_js_buffer_frames=function(){return(g.___em_js__saudio_js_buffer_frames=g.asm.cc).apply(null,arguments)};
g.__sargs_add_kvp=function(){return(g.__sargs_add_kvp=g.asm.dc).apply(null,arguments)};g.___em_js__sargs_js_parse_url=function(){return(g.___em_js__sargs_js_parse_url=g.asm.ec).apply(null,arguments)};g.___em_js__simgui_js_is_osx=function(){return(g.___em_js__simgui_js_is_osx=g.asm.fc).apply(null,arguments)};g.___errno_location=function(){return(g.___errno_location=g.asm.gc).apply(null,arguments)};
var Hc=g._realloc=function(){return(Hc=g._realloc=g.asm.hc).apply(null,arguments)},Bd=g._setThrew=function(){return(Bd=g._setThrew=g.asm.ic).apply(null,arguments)},Ld=g.dynCall_v=function(){return(Ld=g.dynCall_v=g.asm.jc).apply(null,arguments)},Md=g.dynCall_iii=function(){return(Md=g.dynCall_iii=g.asm.kc).apply(null,arguments)},Aa=g.stackSave=function(){return(Aa=g.stackSave=g.asm.lc).apply(null,arguments)},za=g.stackAlloc=function(){return(za=g.stackAlloc=g.asm.mc).apply(null,arguments)},Ba=g.stackRestore=
function(){return(Ba=g.stackRestore=g.asm.nc).apply(null,arguments)};g.dynCall_vi=function(){return(g.dynCall_vi=g.asm.oc).apply(null,arguments)};var Jc=g.dynCall_iiii=function(){return(Jc=g.dynCall_iiii=g.asm.pc).apply(null,arguments)},Cd=g.dynCall_idi=function(){return(Cd=g.dynCall_idi=g.asm.qc).apply(null,arguments)};function Fd(a){var b=Aa();try{Ld(a)}catch(c){Ba(b);if(c!==c+0&&"longjmp"!==c)throw c;Bd(1,0)}}
function Ed(a,b,c){var d=Aa();try{return Md(a,b,c)}catch(e){Ba(d);if(e!==e+0&&"longjmp"!==e)throw e;Bd(1,0)}}g.asm=Kd;var Nd;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ya=function Od(){Nd||Pd();Nd||(Ya=Od)};
function Pd(a){function b(){if(!Nd&&(Nd=!0,!wa)){g.noFSInit||ec||(ec=!0,dc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?hc("stdin",g.stdin):ac("/dev/tty","/dev/stdin"),g.stdout?hc("stdout",null,g.stdout):ac("/dev/tty","/dev/stdout"),g.stderr?hc("stderr",null,g.stderr):ac("/dev/tty1","/dev/stderr"),Ab("/dev/stdin","r"),Ab("/dev/stdout","w"),Ab("/dev/stderr","w"));La(Na);Kb=!1;La(Oa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Qd){var c=a,d=g._main;c=c||[];var e=c.length+
1,f=za(4*(e+1));B[f>>2]=Fa(da);for(var h=1;h<e;h++)B[(f>>2)+h]=Fa(c[h-1]);B[(f>>2)+e]=0;try{var m=d(e,f);Dd(m,!0)}catch(t){t instanceof pa||("unwind"==t?ta=!0:((c=t)&&"object"===typeof t&&t.stack&&(c=[t,t.stack]),p("exception thrown: "+c),ea(1,t)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Qa.unshift(c);La(Qa)}}a=a||ca;if(!(0<Wa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ra();La(Ma);
0<Wa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Pd;function Dd(a,b){if(!b||!ta||0!==a){if(!ta&&(wa=!0,g.onExit))g.onExit(a);ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Qd=!0;g.noInitialRun&&(Qd=!1);ta=!0;Pd();
